name: 'OpenAPI Lint Action'
description: 'Use OpenAPI Linter in GitHub Actions'
inputs:
  file:
    required: true
    description: 'Path to file to lint'
  github_token:
    required: true
    description: 'GitHub Personal Access Token'
runs:
  using: 'node16'
  main: 'dist/index.js'
