name: "OpenApi lint"

on:
  push:
    branches: [ master, release* ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  openapi-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: OpenAPI lint check
        uses: nwestfall/openapi-action@v1.0.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./specification/protocol/open_inference_rest.yaml

  grpc-proto-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Setup buf
        uses: bufbuild/buf-setup-action@v1

      - name: run buf lint
        uses: bufbuild/buf-lint-action@v1
        with:
          input: ./specification/protocol
